### ISSUE TITLE
Viewing the virtual container of the lands plugin will cause the server to crash

### ISSUE THREAD

**Issue by jhqwqmc** [PluginBugs/Issues-ChestPreview#15]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jhqwqmc#8740

### What happened?

When I look at the container created by the lands plugin, it automatically triggers the right-click to open and crashes the server instantly.
And it will cause inexplicable right-clicking caused by non-player operations.

### Steps to reproduce the issue

https://github.com/PluginBugs/Issues-ChestPreview/assets/113768629/63174fe0-1c55-44a0-ac36-840bd9e30296

### Server version

git-Purpur-2095 (MC: 1.20.2)*

### ChestPreview Version

1.0.6

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

[2024-01-10-9.log.gz](https://github.com/PluginBugs/Issues-ChestPreview/files/13886736/2024-01-10-9.log.gz)
[crash-2024-01-10_18.48.38-server.txt](https://github.com/PluginBugs/Issues-ChestPreview/files/13886740/crash-2024-01-10_18.48.38-server.txt)

**Comment by LoneDev6** [comment]
This will be fixed, thanks

**Comment by jhqwqmc** [comment]
It seems that the repair is not perfect.

**Comment by jhqwqmc** [comment]
Each preview triggers a virtual placement of blocks

**Comment by jhqwqmc** [comment]
https://github.com/PluginBugs/Issues-ChestPreview/assets/113768629/312de7a8-e60d-4fe4-a6ca-77973c5caa63

**Comment by jhqwqmc** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
Is this causing any real gameplay issue?
This is normal as I have to use a way to check if the player has actual permission to open the container.
In this case I don't trigger the interaction anymore because it causes issues with plugins, now I trigger a fake block place event and check if it's cancelled by protection plugins.

Please let me know if it actually creates any issue.
Note: this can be disabled in config.yml: `check_container_access_permission: false`

**Comment by jhqwqmc** [comment]
This could definitely cause some issues, because right now it's in notification mode. If I switch it to lock mode, the plugin will automatically lock some containers that I don't want to lock. Can you provide an API so I can notify other plugin developers to capture this event and cancel some unwanted actions?

**Comment by jhqwqmc** [comment]
I just changed check_container_access_permission to false but it still triggers like in the video.

**Comment by jhqwqmc** [comment]
Through testing, this method does not correctly check whether the player has permission to open the box, and can still be displayed to players who do not have permission to open it.

**Comment by LoneDev6** [comment]
I made a mistake in the configuration, i will fix it later, i wrote `optimization` two times in my code.
For now edit it like that:

```yml
optimization:
  container_detection_interval_ticks: 1
  optimization:
    check_container_access_permission: false
```

**Comment by jhqwqmc** [comment]
Can you judge directly through the API of this plugin?
In this way, there is no need to open or place to determine whether there is permission.
[ChestProtectAPI](https://github.com/Angeschossen/ChestProtectAPI)

**Comment by LoneDev6** [comment]
Hooking into protection plugins is tedious as it increases the build time of the plugin.
For example to build my other plugin ItemsAdder it takes 25 seconds each time I have to make a minor change during my development phase.
ItemsAdder hooks into more than 20 plugins.

I'd prefer to avoid hooking into protection plugins. The fake event is a trick used by many plugins to achieve that.
Please let me know if the current trick is causing any gameplay issue, I might find another solution for that.

An idea would be to write a proper API to check for protection plugins, similar to [this](https://www.spigotmc.org/resources/%E2%9B%94-protectionlib-ensure-your-players-can-build.95058/), but I don't really think it's a clean solution to hook every possible plugin.

**Comment by jhqwqmc** [comment]
However, fake events do have certain compatibility issues, but I don’t have any better ideas.
