### ISSUE TITLE
Could not pass event PlayerMoveEvent to ChestPreview v1.0.6-r2

### ISSUE THREAD

**Issue by BerndPixel** [PluginBugs/Issues-ChestPreview#16]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After installing the plugin, I got this error when I looked at a box. Unfortunately the same error with the previous version. 

### Steps to reproduce the issue

1. Install the Plugin
2. Update LoneLibs & ProtocolLib
3. Start the Server
4. Error was in Console

### Server version

Paper 1.20.1 R0.1 | git-Paper 182

### ChestPreview Version

1.0.6-r2

### ProtocolLib Version

5-2-0-Snapshot 679

### LoneLibs Version

1.0.45

### FULL server log

https://pastebin.com/R3uiWTPP

### Error (optional)

```shell
https://pastebin.com/mqFD2kHP
```

**Comment by LoneDev6** [comment]
Update Paper to the latest build for 1.20.1.
https://papermc.io/downloads/all

For some reason a method used by the plugin is not as it should be, I suspect it's because you're using an old build (182 is not the latest).

**Comment by BerndPixel** [comment]
Tested with the latest 1.20.1 paper, unfortunately the same problem.

**Comment by LoneDev6** [comment]
Will be checked, but it's strange as checking the code and it's not private.
![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/27242001/ec4b4fc6-4e75-4940-bd55-53bc9cad92dd)

Is it possible for you to move to 1.20.2?

**Comment by BerndPixel** [comment]
No, currently 1.20.2 or 1.20.4 is not yet possible, as I do not yet have an update for many plugins. The log you can see above is the test server. This is, so to speak, a mirror of the normal servers.
