### ISSUE TITLE
Not deleted display

### ISSUE THREAD

**Issue by jhqwqmc** [PluginBugs/Issues-ChestPreview#22]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jhqwqmc#8740

### What happened?

Not deleted display

### Steps to reproduce the issue

1.look at the chest
2.Click shift and then release it, then click again, and repeat while moving the cursor to the chest, then move away and look again, then repeat.

### ChestPreview Version

[01:30:04 INFO]: ChestPreview version 1.0.7

### ProtocolLib Version

[01:29:54 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[01:29:54 INFO]: Provides read/write access to the Minecraft protocol.
[01:29:54 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:29:38 INFO]: LoneLibs version 1.0.45
[01:29:38 INFO]: Collection of libs used by my plugins
[01:29:38 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
graphics:
  trigger_distance_blocks: 4
  show_title: true
  brightness:
    block_light: 15
    sky_light: 15
  position:
    distance_y: 0.2
    distance_front: -1.0
  show_on_poses:
    standing: false
    sneaking: true
    crawling: false
    swimming: false
optimization:
  container_detection_interval_ticks: 1
  check_container_access_permission: true
  commands:
    toggle_enable_disable: true
containers:
  ender_chest: true
  jukebox: true
worlds:
- '*'
messages:
  toggle_enable_disable: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ChestPreview/assets/113768629/c4ad308c-1d0b-4b41-92c2-2c22c68e407d

**Comment by jhqwqmc** [comment]
If you look at the chest and press shift, you can see the other side of the chest, and then press shift repeatedly to trigger this bug.

**Comment by jhqwqmc** [comment]
![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/113768629/67aa0dbd-cd5d-42f6-bfb1-64a8aefc6b3c)

**Comment by LoneDev6** [comment]
It's not clear, please make a full video showcasing how to reproduce the issue.
Thanks

**Comment by jhqwqmc** [comment]
> It's not clear, please make a full video showcasing how to reproduce the issue.
Thanks

https://www.dropbox.com/scl/fi/mu5e2ndrbopmdal82lwx3/QQ202422-202025-HD.mp4?rlkey=ebqidxbw3to4qq2u7zfvvtayb&dl=0

**Comment by LoneDev6** [comment]
So this happens only when you spam shift while looking at a chest, correct?

**Comment by jhqwqmc** [comment]
This happens when you point to another side of the block when pressing shift.

**Comment by jhqwqmc** [comment]
and when you release shift, you return to the previous side of the block.

**Comment by LoneDev6** [comment]
Fixed, thanks

https://github.com/PluginBugs/Issues-ChestPreview/assets/27242001/040fdeff-28e5-4531-a44c-69211d241128
