### ISSUE TITLE
Allow disabling permission check to see preview even if player has no build permission

### ISSUE THREAD

**Issue by TylorTurner** [PluginBugs/Issues-ChestPreview#23]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

tylorturner

### Describe the solution you'd like

Can you add compatibility for Towny allowing Town/Nation Enemies or Non Allies to ChestPreview Chests? I was hoping this was possible as I was looking for a solution to help players raid each other. 

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No other way I know to allow non residents to safely peer in to chests without being able to steal.

**Comment by LoneDev6** [comment]
So you want people to be able to view chests contents of chests they don't have permission to open?

**Comment by TylorTurner** [comment]
Yes, exactly. It would be neat to allow the enemy team to view contents of
the chests.

**Comment by TylorTurner** [comment]
After the last update ChestPreview does not seem to work at all

**Comment by LoneDev6** [comment]
> After the last update ChestPreview does not seem to work at all

can you be more specific?

**Comment by TylorTurner** [comment]
Sorry to come back at you with another issue but it looks like checking inside of chest with Towny does not work. I currently cannot chest preview any chest in another town.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ChestPreview/issues/15#issuecomment-1884934425
Open config.yml and set `check_container_access_permission: false`
