### ISSUE TITLE
Make the messages configurable

### ISSUE THREAD

**Issue by Askarionn** [PluginBugs/Issues-ChestPreview#24]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Make the messages configurable

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

prefix: [ChestPreview]
show-toggle-on: Chest display shown.
show-toggle-off: Chesti display hidden.

etc etc

**Comment by LoneDev6** [comment]
Done!
