### ISSUE TITLE
ChestPreview Will Not Load

### ISSUE THREAD

**Issue by TylorTurner** [PluginBugs/Issues-ChestPreview#30]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tylorturner

### What happened?

chest preview has not worked since the last update.

https://mclo.gs/ZllL4oJ

### Steps to reproduce the issue

Start server with ChestPreview And Dependency

### Server version

PurPur 1.19.4

### ChestPreview Version

1.0.8

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/133236597/389dcc62-f386-4151-94fb-89091798da1d)

**Comment by LoneDev6** [comment]
I think it's because the name of the folder is strange and confuses the plugin.
Rename your folder from `Main%20Server` to `MainServer`

**Comment by TylorTurner** [comment]
Are you talking about my main server folder named MainFolder? It has no % at all in it.
![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/133236597/1b9382f5-8864-4096-978f-d31a400c9ffb)

**Comment by TylorTurner** [comment]
![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/133236597/c1b1b49a-d355-4e63-a484-e4380c0e7614)

**Comment by LoneDev6** [comment]
It's the space i suspect, remove it

**Comment by TylorTurner** [comment]
There is no way this entire month for a damn space. That did it!

**Comment by LoneDev6** [comment]
Yea, this is why I always avoid using special characters other than `_` in my development stuff, they always cause issues and Windows is more inclined to these stupid issues.
Apologizes for the late answer, I'm working hard on my projects.

**Comment by TylorTurner** [comment]
Thank you for helping I know now! Appreciate you.
