### ISSUE TITLE
chestpreview pose/show - allowing to put there player name 

### ISSUE THREAD

**Issue by bobhenl** [PluginBugs/Issues-ChestPreview#32]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hi, can you add a way to put a player name at the end of this? As currently we can't use the command from console etc

### Is your feature request related to a problem?

Yeah, plugin can't be used from console

### Describe alternatives you've considered

no

**Comment by CNWuWeilong** [comment]
Hi author, I'm running paper version 1.20.6 and it stopped working on my server. Can you update it? I really need it!

**Comment by CNWuWeilong** [comment]
Hi author, I'm running paper version 1.20.6 and it stopped working on my server. Can you update it? I really need it!

**Comment by LoneDev6** [comment]
New argument
`/chestpreview show <toggle|enable|disable> [player]`
`/chestpreview pose <all|standing|sneaking|crawling|swimming> <toggle|enable|disable> [player]`
