### ISSUE TITLE
1.20.1 compatibility

### ISSUE THREAD

**Issue by enesop** [PluginBugs/Issues-ChestPreview#4]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Installed plugin, didn't work out of the box

### Steps to reproduce the issue

Install plugin, install dependencies, start server

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### ChestPreview Version

1.0.4

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.30

### Error (optional)

```shell
02.12 20:54:56 [Server] [INFO] java.lang.RuntimeException: This server is not compatible with this plugin.
02.12 20:54:56 [Server] [INFO] at chestpreview.m.e.a(SourceFile:48) ~[ChestPreview_1.0.4.jar:?]
02.12 20:54:56 [Server] [INFO] at chestpreview.m.n.<init>(SourceFile:48) ~[ChestPreview_1.0.4.jar:?]
02.12 20:54:56 [Server] [INFO] at chestpreview.m.n.h(SourceFile:65) ~[ChestPreview_1.0.4.jar:?]
02.12 20:54:56 [Server] [INFO] at dev.lone.chestpreview.Main.onEnable(SourceFile:67) ~[ChestPreview_1.0.4.jar:?]
02.12 20:54:56 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
02.12 20:54:56 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
02.12 20:54:56 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
02.12 20:54:56 [Server] [INFO] at java.lang.Thread.run(Thread.java:1589) ~[?:?]
02.12 20:54:56 [Server] [INFO] [ChestPreview] Disabling ChestPreview v1.0.4
```

**Comment by LoneDev6** [comment]
As shown in the log:
> This server is not compatible with this plugin.

Update to 1.20.2.

**Comment by enesop** [comment]
Your plugin page clearly states this below,
![image](https://github.com/PluginBugs/Issues-ChestPreview/assets/60015283/dfa4444f-2181-425b-ac17-b7d2cd259c1d)
I am not stupid, if it wasn't an issue I wouldn't have opened one, you shouldn't be telling me what version my server needs to be on, you should be fixing your plugin so it works on all versions it is advertised for.

**Comment by LoneDev6** [comment]
Didn't imply that you're stupid but that the plugin doesn't work on 1.20.1.
Tomorrow I will test if I can make it compatible with 1.20.1 but there is no reason to stay on 1.20.1 as it's outdated and Mojang fixed lot of issues on 1.20.2.
If I recall 1.20.1 had some limitations which prevented me from adding compatibility.

**Comment by enesop** [comment]
If you let me know the issues, that directly do not allow you to have the plugin on 1.20.1, then I will use it on the next server update, I need 1.20.1 for specific reasons on my server. Thank you

**Comment by LoneDev6** [comment]
Thanks for the patience, I plan to finish the compatibility addition on it this week but for now has some issues to start on 1.20.1.

**Comment by LoneDev6** [comment]
Should work fine now, i will post an update today!
