### ISSUE TITLE
Incorrect display of items in shulkers

### ISSUE THREAD

**Issue by DxrkCxt** [PluginBugs/Issues-ChestPreview#6]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Incorrect display of items and quantities in the purple shulker block.
![изображение](https://github.com/PluginBugs/Issues-ChestPreview/assets/124828932/4a178320-c305-4637-82f6-ac0b0abd83c7)
![изображение](https://github.com/PluginBugs/Issues-ChestPreview/assets/124828932/c237864c-2d70-46fa-9109-4dcbeeef70a4)

### Steps to reproduce the issue

Put up the shulker.
Put the trapdoors inside
Ask another player to drag to another slot
There's a bug.

### Server version

Purpur 1.20.2 build 95

### ChestPreview Version

ChestPreview version 1.0.4

### ProtocolLib Version

Protocollib 5.1.1 build 673

### LoneLibs Version

LoneLibs 1.0.31

### FULL server log

No errors or warns in console

**Comment by DxrkCxt** [comment]
Addition information: It broke all the shulkers

UPD: Fixed it with a world change
![изображение](https://github.com/PluginBugs/Issues-ChestPreview/assets/124828932/9934edc0-dd63-452f-92d6-255322d9c8ae)
![изображение](https://github.com/PluginBugs/Issues-ChestPreview/assets/124828932/e9a4ce4c-68e3-4dc2-80fa-452da4a5be67)
![изображение](https://github.com/PluginBugs/Issues-ChestPreview/assets/124828932/8a6d77e1-28d7-4fa8-ad96-58056573eeee)

**Comment by LoneDev6** [comment]
Interesting, I will make some tests, very strange indeed!

**Comment by DxrkCxt** [comment]
by LoneDev:
Message moved to #14
