### ISSUE TITLE
Add Show On Poses command selector

### ISSUE THREAD

**Issue by Askarionn** [PluginBugs/Issues-ChestPreview#9]
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add a command to select in which pose you should see the preview
Example: /chestpreview pose standing/sneaking/crawling/swimming/all (should be per player not global)
Also a placeholder to see which pose you selected would be useful

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

-

**Comment by LoneDev6** [comment]
I think the command should be like that: `/chestpreview pose <pose|all> <true|false>`
So people can decide multiple poses.

**Comment by Askarionn** [comment]
Sure, sounds good!
